# Generated by Django 5.1.4 on 2025-05-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_topicresult_total_questions_alter_topicresult_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='role',
        ),
    ]
