# Generated by Django 5.1.4 on 2025-05-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_topicresult_total_questions_alter_topicresult_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='form.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('activity_id', models.IntegerField()),
                ('activity_type', models.CharField(max_length=50)),
                ('user_response', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='prueba.subtopico')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='form.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.FloatField(default=0)),
                ('puntaje_total', models.FloatField(default=0)),
                ('porcentaje', models.FloatField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='prueba.topico')),
            ],
        ),
    ]
