# Generated by Django 5.1.4 on 2025-04-11 15:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción múltiple'), ('vf', 'Verdadero o falso'), ('seleccion_multiple', 'Seleccionar varias opciones'), ('completar', 'Completar espacios'), ('respuesta_libre', 'Respuesta libre')], max_length=50)),
                ('titulo', models.TextField()),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('opciones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('respuesta_correcta', models.JSONField()),
                ('respuesta_usuario', models.JSONField(blank=True, null=True)),
                ('puntaje_total', models.FloatField(default=1.0)),
                ('puntaje_obtenido', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subtopico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='prueba.subtopico')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='accounts.role')),
            ],
        ),
        migrations.AddField(
            model_name='subtopico',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopicos', to='prueba.topico'),
        ),
        migrations.CreateModel(
            name='ResultadoTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_obtenido', models.FloatField(default=0)),
                ('puntaje_total', models.FloatField(default=0)),
                ('porcentaje', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='prueba.topico')),
            ],
        ),
    ]
