# Generated by Django 5.1.4 on 2025-05-27 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0003_remove_topic_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subtopico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('activity_type', models.CharField(choices=[('image_select', 'Image Select'), ('checkbox', 'Checkbox'), ('text_input', 'Text Input'), ('select', 'Select'), ('other', 'Other')], default='text_input', max_length=20)),
                ('question', models.TextField()),
                ('subquestion', models.TextField()),
                ('options', models.JSONField(blank=True, help_text='Lista de opciones si aplica', null=True)),
                ('correct_answer', models.JSONField(default=list, help_text='Respuesta(s) correcta(s) según el tipo')),
                ('custom_style', models.TextField(blank=True, help_text='CSS opcional', null=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='prueba.subtopico')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.topic')),
            ],
        ),
        migrations.AddField(
            model_name='subtopico',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.topico'),
        ),
        migrations.CreateModel(
            name='UserActivityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prueba.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
