# Generated by Django 5.1.4 on 2025-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='user',
        ),
        migrations.AddField(
            model_name='actividad',
            name='opciones_imagenes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('seleccion_multiple', 'Selección Múltiple'), ('seleccion_imagenes', 'Selección de Imágenes'), ('vf', 'Verdadero/Falso'), ('completar', 'Completar'), ('respuesta_libre', 'Respuesta Libre')], max_length=50),
        ),
    ]
