# Generated by Django 5.1.4 on 2025-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
