# Generated by Django 5.1.4 on 2025-06-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_topic_role'),
        ('prueba', '0002_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopico',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.topic'),
        ),
        migrations.DeleteModel(
            name='Topico',
        ),
    ]
